os:
  - linux
# not yet  - osx

sudo: required

language: node_js

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - "4"
  - "6"

git:
  submodules: false  

before_install:
  - git submodule update --depth 50 --init --recursive

before_install:
  # sudo apt-get install liboce-ocaf-dev liboce-modeling-dev liboce-foundation-dev ; 
  # git clone http://github.com/tpaviot/oce.git ;
  # cat /proc/cpuinfo ;
  sh ./prepare_build.sh
  
  
  
  

  
   
  
  


