install:
  - cmd: build.bat
environment:
  nodejs_version: "0.12"
  msvs_toolset: 12
  VisualStudioVersion: "12"
platform:
  - x86

init:
  - git config --global core.autocrlf input
configuration:
  - Release
test_script:
  - node --version
  - npm test
build: off
deploy: off

