init:
  - git config --global core.autocrlf input
  - Install-Product node '6' x64

# clone directory
clone_folder: c:\projects\node-occ

clone_depth: 5

install:
  - cmd: build.bat
  
  
environment:
  nodejs_version: "6.3"
  msvs_toolset: 14
  VisualStudioVersion: "14"
# 14 : Visual Studio 2015 , 12 VisualStudio 2013
platform:
  - x64


configuration:
  - Release
test_script:
  - node --version
  - npm install mocha -g
  - npm install node-gyp
  - npm test
build: off
deploy: off

