init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\node-occ

clone_depth: 5

install:
  - ps: Install-Product node '6' x64
  - cmd: build.bat
  

cache:
  - c:\projects\node-occ\oce
  - c:\projects\node-occ\build_oce_2015_Win64
  - c:\OCE-0.17.2

environment:
  nodejs_version: "6.3"
  msvs_toolset: 14
  VisualStudioVersion: "14"
# 14 : Visual Studio 2015 , 12 VisualStudio 2013
platform:
  - x64


configuration:
  - Release
test_script:
  - node --version
  - npm install mocha -g
  - npm install node-gyp
  - npm test
build: off
deploy: off

