install:
  - cmd: build.bat
environment:
  matrix:
    - nodejs_version: "0.12"
platform:
  - x86
  - msvs_toolset: "12"
init:
  - git config --global core.autocrlf input
os: "Visual Studio 2012"
configuration:
  - Release
test_script:
  - node --version
  - npm test
build: off
deploy: off

