init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\node-occ

install:
  - cmd: build.bat
  
  
environment:
  nodejs_version: "0.12"
  msvs_toolset: 12
  VisualStudioVersion: "12"
platform:
  - x86

configuration:
  - Release
test_script:
  - node --version
  - npm install mocha -g
  - npm test
build: off
deploy: off

