install:
  - cmd: build.bat
environment:
  matrix:
    - nodejs_version: "0.12"
      msvs_toolset: 12
platform:
  - x86

init:
  - git config --global core.autocrlf input
os: "Visual Studio Express 2012 for Windows Desktop"
configuration:
  - Release
test_script:
  - node --version
  - npm test
build: off
deploy: off

